version: '3'
services:
  web:
    image: momureithi/my-basic-microservice:0.2
    container_name: my-basic-microservice-container
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo