- name: Containerize and run the e-commerce application using Ansible
  hosts: all
  become: true
  roles:
    - clone-repository
    - docker-setup
    - network-setup
    - database-setup
    - frontend-setup
    - backend-setup