---
# tasks file for docker-setup
- name: Docker Installation
  apt:
    name: docker.io
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
  become: yes

- name: Create and run a Docker container
  command: docker run -d -p 3000:3000 momureithi/my-basic-microservice:0.2.0